api:
    resource:
        path: ../src/Controller/api
        namespace: App\Controller\api
    prefix: '/api'
    name_prefix: 'api_'
    type: attribute

entry_point:
    path: /
    controller: App\Controller\EntryPointController::loadAppAction

app:
    path: /{route}
    controller: App\Controller\EntryPointController::loadAppAction
    requirements:
        route: '^.+'
